# Site settings
title               : Dylan the Data Dude
description         : "I don't dance I make data moves." Welcome! I am Dylan, a data enginner. This is where I post some of my thoughts, stories of my doings and goings and showcase things I create.
baseurl             : ""
repository          : https://github.com/dylan-kuo

# Navbar settings
nav_exclude:
  - pages/404.html
  - pages/index.md

# Author info
author:
  name              : Dylan Kuo
  image             : 
  email             : dylan.t.kuo@gmail.com
  twitter           : dylantkuo
  github            : dylan-kuo
  linkedin          : dylankuo

# Posts
permalink: /:title

# Collections
collections:
  projects:
    output: true

# Disqus
disqus:

# Analytics
analytics:
  enabled: false
  google:
    tracking_id: 

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Exclude from processing
exclude:
  - README.md
  - "*.log"
  
