# Site settings
title               : Dylan the Data Dude
description         : I don't dance now I make data move. Welcome! I am Dylan, a Data Enginner located in Boston, Massachusetts. This is where I post some of my thoughts, stories of my doings and goings and showcase things I create.
baseurl             : ""
repository          : https://github.com/dylan-kuo

# Navbar settings
nav_exclude:
  - pages/404.html
  - pages/index.md

# Author info
author:
  name              : Dylan Kuo
  image             : /img/dylan_the_data_dude.svg
  email             : dylan.t.kuo@gmail.com
  twitter           : dylantkuo
  github            : dylan-kuo
  linkedin          : dylankuo

# Posts
permalink: /:title

# Collections
collections:
  projects:
    output: true

# Disqus
disqus:

# Analytics
analytics:
  enabled: true
  google:
    tracking_id: G-3N397L69L8

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Exclude from processing
exclude:
  - README.md
  - "*.log"

plugins: - jekyll-sitemap