# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dylan Kuo
baseurl:        ""
url:            "https://dylan-kuo.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Dylan Kuo
  url:          https://dylan-kuo.github.io/
  email:        dylan.t.kuo@gmail.com  
  github:       dylan-kuo
  twitter:      DylanTKuo

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/dylan-kuo/dylan-kuo.github.io